import pytest

def test_final_review_agent_aggregation():
    # Arrange: Import FinalReviewAgent from review_bot package
    try:
        from src.review_bot.final_agent import FinalReviewAgent
    except ImportError:
        pytest.fail("TDD Check: FinalReviewAgent class is not implemented yet in src.review_bot.final_agent")
        
    agent = FinalReviewAgent()
    
    # Outputs generated by downstream review agents
    logic_review = """## Logic Review
### Findings
- Severity: High
- File: src/calculator.py
- Description: Calculator division by zero is not handled correctly.
- Evidence: Returning None or passing instead of raising ValueError.
- Recommendation: Ensure that ValueError is raised when dividing by zero."""
    
    security_review = """## Security Review
For each issue:
- Severity: Critical
- File: src/database.py
- Issue: Hardcoded credentials
- Evidence: password=secret_pass host=localhost
- Recommendation: Use environment variables or secret vaults instead of hardcoding credentials in source files."""

    test_review = "Test coverage is sufficient."
    quality_review = "No code quality issues detected."
    dependency_review = "No dependency issues detected."
    cicd_review = "No CI/CD issues detected."
    docs_review = "No documentation updates required."
    
    # Act: Aggregate findings into a final report
    final_output = agent.aggregate(
        logic=logic_review,
        security=security_review,
        test=test_review,
        quality=quality_review,
        dependency=dependency_review,
        cicd=cicd_review,
        docs=docs_review
    )
    
    # Assert: Output formatted cleanly, calculates high risk, and requests changes
    assert "# Pull Request Review" in final_output
    assert "Overall Risk: High" in final_output or "Overall Risk: Critical" in final_output
    assert "Request Changes" in final_output
    assert "calculator.py" in final_output
    assert "database.py" in final_output

def test_final_review_agent_approve():
    # Arrange
    try:
        from src.review_bot.final_agent import FinalReviewAgent
    except ImportError:
        pytest.fail("TDD Check: FinalReviewAgent class is not implemented yet")
        
    agent = FinalReviewAgent()
    
    # Inputs with zero flagged issues
    final_output = agent.aggregate(
        logic="No logic issues detected.",
        security="No security issues detected.",
        test="Test coverage is sufficient.",
        quality="No code quality issues detected.",
        dependency="No dependency issues detected.",
        cicd="No CI/CD issues detected.",
        docs="No documentation updates required."
    )
    
    # Assert
    assert "Overall Risk: Low" in final_output
    assert "Approve" in final_output
